import { jsPDF } from "jspdf";
import { AgentResult } from "@/components/ResultsPanel";

export interface ExportData {
  mission: string;
  results: AgentResult[];
  completedAt: Date;
}

export const exportToMarkdown = (data: ExportData): string => {
  const date = data.completedAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  let markdown = `# Mission Report\n\n`;
  markdown += `**Mission:** ${data.mission}\n\n`;
  markdown += `**Completed:** ${date}\n\n`;
  markdown += `---\n\n`;
  markdown += `## Agent Results\n\n`;

  data.results.forEach((result) => {
    markdown += `### ${result.agentName}\n\n`;
    markdown += `${result.result}\n\n`;
    markdown += `---\n\n`;
  });

  markdown += `\n*Generated by AI Agent Workforce Platform*`;

  return markdown;
};

export const downloadMarkdown = (data: ExportData) => {
  const markdown = exportToMarkdown(data);
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `mission-report-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportToPDF = (data: ExportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Mission Report", margin, yPos);
  yPos += 15;

  // Mission
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Mission:", margin, yPos);
  yPos += 7;
  doc.setFont("helvetica", "normal");
  const missionLines = doc.splitTextToSize(data.mission, maxWidth);
  doc.text(missionLines, margin, yPos);
  yPos += missionLines.length * 6 + 5;

  // Date
  const date = data.completedAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.setFont("helvetica", "italic");
  doc.text(`Completed: ${date}`, margin, yPos);
  yPos += 15;

  // Separator
  doc.setDrawColor(200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Results
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Agent Results", margin, yPos);
  yPos += 10;

  data.results.forEach((result) => {
    // Check if we need a new page
    if (yPos > 260) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(result.agentName, margin, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const resultLines = doc.splitTextToSize(result.result, maxWidth);
    
    // Check if result would overflow page
    const resultHeight = resultLines.length * 5;
    if (yPos + resultHeight > 280) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.text(resultLines, margin, yPos);
    yPos += resultHeight + 10;

    // Small separator between agents
    if (yPos < 270) {
      doc.setDrawColor(230);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 8;
    }
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text(
      "Generated by AI Agent Workforce Platform",
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin - 20,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  doc.save(`mission-report-${Date.now()}.pdf`);
};
